import { Product } from './types';

export const categories = [
  'Todos',
  'Rostro',
  'Ojos',
  'Labios',
  'Skincare',
  'Accesorios'
];

export const products: Product[] = [
  {
    id: 'p1',
    name: 'Base Líquida Luminosa',
    description: 'Base de cobertura media a alta con acabado radiante y natural. Larga duración.',
    price: 350,
    wholesalePrice: 250,
    wholesaleMin: 6,
    category: 'Rostro',
    image: 'https://images.unsplash.com/photo-1631214500115-598fc2cb8d2d?auto=format&fit=crop&q=80&w=800',
    isNew: true,
  },
  {
    id: 'p2',
    name: 'Paleta de Sombras "Sunset"',
    description: '12 tonos cálidos altamente pigmentados, perfectos para looks de día y de noche.',
    price: 480,
    wholesalePrice: 320,
    wholesaleMin: 5,
    category: 'Ojos',
    image: 'https://images.unsplash.com/photo-1512496115851-a408e8cece92?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'p3',
    name: 'Labial Mate Velvet',
    description: 'Labial líquido de acabado mate aterciopelado. No reseca los labios.',
    price: 180,
    wholesalePrice: 110,
    wholesaleMin: 10,
    category: 'Labios',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'p4',
    name: 'Sérum Hidratante Ácido Hialurónico',
    description: 'Sérum facial para una hidratación profunda y reducción de líneas de expresión.',
    price: 520,
    wholesalePrice: 380,
    wholesaleMin: 4,
    category: 'Skincare',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800',
    isNew: true,
  },
  {
    id: 'p5',
    name: 'Set de Brochas Profesionales',
    description: 'Set de 10 brochas de cerdas sintéticas ultra suaves con estuche.',
    price: 650,
    wholesalePrice: 450,
    wholesaleMin: 3,
    category: 'Accesorios',
    image: 'https://images.unsplash.com/photo-1596462502278-27bf85033e5a?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'p6',
    name: 'Máscara de Pestañas Volumen Extremo',
    description: 'Fórmula a prueba de agua que aporta volumen y longitud sin grumos.',
    price: 220,
    wholesalePrice: 150,
    wholesaleMin: 6,
    category: 'Ojos',
    image: 'https://images.unsplash.com/photo-1631214503851-bc81e2812285?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'p7',
    name: 'Rubor en Crema',
    description: 'Rubor de textura suave que se funde con la piel para un aspecto saludable.',
    price: 210,
    wholesalePrice: 140,
    wholesaleMin: 8,
    category: 'Rostro',
    image: 'https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'p8',
    name: 'Gloss Labial Brillo 3D',
    description: 'Brillo labial no pegajoso con efecto volumen y destellos sutiles.',
    price: 160,
    wholesalePrice: 95,
    wholesaleMin: 12,
    category: 'Labios',
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
  }
];
